# Welcome to Jekyll!

# Website settings
title: Athul Paul Jacob
description: Athul Paul Jacob's blog
keywords: 
baseurl: 
url: http://apjacob.github.io  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /static/assets/img/blog  

author:  
  name: GitHub  
  first_name: Athul Paul  
  last_name: Jacob  
  avatar: /static/assets/img/landing/avatar.jpg 
  github_username: apjacob 
  linkedin_id: apjacob 
  facebook_username: apjacob0307  
  scholar_userid: XT3E7RoAAAAJ
  twitter_username:  
  email:   apjacob@edu.uwaterloo.ca
  cv:   
  skill_icon1:
    - name: icon-python
    - name: icon-scala
  skill_icon2:
    - name: icon-shell
    - name: icon-cplusplus
  desc: I am a senior undergraduate at the University Of Waterloo pursuing Computer Science, Combinatorics and Optimization advised by Prof. Pascal Poupart as well as a visiting researcher at Mila supervised by Prof. Yoshua Bengio. During the fall of 2018, I was a research intern at Facebook AI Research New York mentored by Prof. Kyunghyun Cho. I have previously spent time at Microsoft Research Montreal with Dr. Adam Trischler and Dr. Alessandro Sordoni. I am primarily interested in developing machine learning (ML) models that are capable of lifelong learning, few-shot learning, reasoning, and adaptive computation in the context of natural language.
# comment
# disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
#   name: jalpc

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  id: UA-131687311-1

## google optimize
go:
  # id:

# ## growingIO
# gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
#   # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: on  # index page carousel switch
blog_carousel: off  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-gist

